# Generated by Django 4.1.7 on 2023-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=360, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='producto/imagenes/')),
                ('contenido', models.TextField(default='', verbose_name='Contenido')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
