# Generated by Django 4.1.7 on 2023-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='inicio',
            field=models.BooleanField(default=False, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to='publicacion/imagenes/'),
        ),
    ]
