# Generated by Django 4.2.3 on 2023-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_publicacion_inicio_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.CharField(default='', max_length=1200, verbose_name='Url'),
        ),
    ]
