# Generated by Django 4.1.7 on 2023-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='', max_length=360, verbose_name='Pais')),
                ('bandera', models.CharField(default='', max_length=1200, verbose_name='Bandera')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default='', max_length=360, verbose_name='Producto')),
                ('imagen', models.ImageField(upload_to='producto/imagenes/')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('Alimentos', 'Alimentos y Bebidas'), ('Suplementos', 'Suplementos'), ('Cuidado', 'Cuidado Personal'), ('Electrodomesticos', 'Electrodomésticos')], default='Alimentos', max_length=20, verbose_name='Categoría')),
                ('pais', models.CharField(default='peru', max_length=360, verbose_name='Pais')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
            ],
        ),
    ]
