# Generated by Django 4.2.3 on 2023-09-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(default='', max_length=1200, verbose_name='Url'),
        ),
    ]
