# Generated by Django 4.2.3 on 2023-09-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_imagen_alter_producto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(default='', max_length=1200, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(default='', max_length=360, verbose_name='Producto'),
        ),
    ]
